"""
Shared execution state for the Deep Agent system.

This state is used only for workflow execution.
Conversation, datasets, analyses and reports are stored
inside MemoryStore.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from models.task import Task


@dataclass
class AgentState:
    """
    Execution state for one workflow.
    """

    # Dataset
    csv_path: Optional[str] = None
    dataframe: Any = None

    # Planning
    current_plan: List[str] = field(default_factory=list)

    # Tasks
    task_queue: List[Task] = field(default_factory=list)
    completed_tasks: List[Task] = field(default_factory=list)
    failed_tasks: List[Task] = field(default_factory=list)

    # Temporary execution memory
    memory: Dict[str, Any] = field(default_factory=dict)

    # Final response generated by the workflow
    final_response: Optional[str] = None

    def add_task(self, task: Task):
        self.task_queue.append(task)

    def complete_task(self, task: Task):
        if task in self.task_queue:
            self.task_queue.remove(task)
        self.completed_tasks.append(task)

    def fail_task(self, task: Task):
        if task in self.task_queue:
            self.task_queue.remove(task)
        self.failed_tasks.append(task)

    def set_memory(self, key: str, value: Any):
        self.memory[key] = value

    def get_memory(self, key: str, default=None):
        return self.memory.get(key, default)

    def clear(self):
        self.task_queue.clear()
        self.completed_tasks.clear()
        self.failed_tasks.clear()
        self.current_plan.clear()
        self.memory.clear()
        self.final_response = None